.Dd $Mdocdate: September 16 2023 $
.Dt NNCARDS 1
.Os
.Sh NAME
.Nm nncards
.Nd TUI flashcard program
.Sh SYNOPSIS
.Nm nncards
.Op Fl trhv
.Op Fl c Ar n
.Ar file
.Sh DESCRIPTION
.Nm
is a program that interprets a given card file and displays the parsed cards
in a simple TUI.
.Nm
was developed with simplicity and portability in mind.
.Pp
.Nm
files are formatted plain-text files. The following is a quick guide to
formatting
.Nm
files:
.Bl -bullet
.It
Each non-blank or non-comment line must contain a term and definition,
seperated by a colon (:) character. Any whitespace between the colon and
definition is ignored. Here is how you would format a card line:
.Pp
term1: Definition of term1.
.It
Lines starting with a hash (#) are interpreted as comments and ignored.
.It
Blank lines are ignored.
.It
Lines that do not contain valid terms/definitions are ignored.
.El
.Pp
.Em example.cards
contains an example card file which you can consult if you wish to see how
a card file is formatted.
.Pp
.Nm
is controlled through various keys:
.Pp
.Bl -column
.It Right Arrow, l, c Ta Ta Next card
.It Left Arrow, h, z Ta Ta Previous card
.It Space, x Ta Ta Ta Ta Flip card
.It Page Down, d Ta Ta Ta Go to final card
.It Page Up, a Ta Ta Ta Go to beginning card
.It Escape, q Ta Ta Ta Ta Quit
.Pp
.Nm
has the following options:
.Bl -tag -width Ds
.It Fl c Ar n
Start at the
.Ar nth
card. If
.Ar n
is greater than the total number of cards, start at
the first card.
.It Fl r
Randomize the order the cards appear in.
.It Fl t
Show terms first rather than definitions.
.It Fl h
Print help message.
.It Fl v
Print
.Nm
version.
.El
.Sh AUTHORS
Written by Samuel Young.
.Sh BUGS
Probably some. Report bugs on my Codeberg,
.Em https://codeberg.org/1-1sam
